# Mutate events to be suitable for pushing to Cloudwatch Logs
filter {
  if "journald" in [tags] {
    # check if message looks like json and try to decode it
    if [message] =~ /^\{.*\}$/ {
      json {
        source => "message"
        target => "message"
      }
    }

    # Move certain(useful) fields under message field
    mutate {
      rename => { "message" => "[message][message]" }
    }

    if [_cmdline] {
      mutate {
        rename => { "_cmdline" => "[message][cmdline]" }
      }
    }
    if [_transport] {
      mutate {
        rename => { "_transport" => "[message][transport]" }
      }
    }
    if [_systemd_unit] {
      mutate {
        rename => { "_systemd_unit" => "[message][systemd_unit]" }
      }
    }

    json_encode {
      source => "message"
      add_tag => ["json_encoded"]
    }
  }
}

output {
  if "json_encoded" and "journald" in [tags] {
    cloudwatchlogs {
      region => "%AWS_REGION%"
      log_group_name => "%LOG_GROUP_NAME%"
      log_stream_name => "journald/%LOG_STREAM_NAME%"
    }
  }
}
